1) List of Cryptocurrencies
jhonnierandrey/rnCryptoViewer pull request #1
Opened 2023-03-23 07:57 UTC by jhonnierandrey

# List of Cryptocurrencies - challenge #1:

This PR includes : 

* Initialization of the React Native application for both iOS and Android.
* Home screen listing Cryptos as in the mockup with hardcoded values.
* Rendering of the hardcoded values follows API data structure for easy implementation.
* Follow theme scheme.
* Main navigation to "Add a Cryptocurrency" screen.
* Navigation back to Home screen.
* Enabling "Add" button when input field is not empty.

Check the [Demo Here](https://drive.google.com/file/d/1TQMH1Rtp0yNcBH6yAFfudoJClwmrBrB5/view?usp=sharing)

2023-03-28 12:57 UTC, FedericoLeiva12 requested changes

2023-03-28 12:57 UTC, FedericoLeiva12 commented on App.tsx
> +    <Fragment>
Fragment is not necessary

2023-03-28 12:57 UTC, FedericoLeiva12 commented on src/components/AddCoin/addCoinStyles.ts
> +        // marginHorizontal: 30,
delete comments

2023-03-28 12:57 UTC, FedericoLeiva12 commented on src/components/AddCoin/addCoinStyles.ts
> +    // btnStatusDisabled:{
delete comments

2023-03-28 12:57 UTC, FedericoLeiva12 commented on src/components/Home/Home.tsx
> +                        <TouchableOpacity onPress={() => { navigation.navigate('AddCoin') }}>
delete brackets in the function

2023-03-28 12:57 UTC, FedericoLeiva12 commented on src/components/ListItem/ListItem.tsx
> +              {' '}
Is this necessary?

2023-03-28 13:15 UTC, jhonnierandrey commented on App.tsx
> +    <Fragment>
Fragment element  and imported removed.

2023-03-28 13:16 UTC, jhonnierandrey commented on src/components/AddCoin/addCoinStyles.ts
> +        // marginHorizontal: 30,
Comments removed.

2023-03-28 13:16 UTC, jhonnierandrey commented on src/components/AddCoin/addCoinStyles.ts
> +    // btnStatusDisabled:{
Comments removed.

2023-03-28 13:16 UTC, jhonnierandrey commented on src/components/Home/Home.tsx
> +                        <TouchableOpacity onPress={() => { navigation.navigate('AddCoin') }}>
Brackets removed.

2023-03-28 13:17 UTC, jhonnierandrey commented on src/components/ListItem/ListItem.tsx
> +              {' '}
Not longer needed, I already added some padding with the styles, `{' '}` removed.

2023-03-30 22:06 UTC, tomasdematos commented on App.tsx
> +const App = () => {
use implicit return 
() => (<....)

2023-03-30 22:08 UTC, tomasdematos commented on src/components/AddCoin/AddCoin.tsx
> +    const [coinTicker, setCoinTicker] = useState<string>('');
type declaration unnecessary:

useState('')

if you declare a initial value, the state will have the type of the default value already

2023-03-30 22:08 UTC, tomasdematos commented on src/components/AddCoin/AddCoin.tsx
> +                        placeholderTextColor={'#666666'}
use the palette

2023-03-30 22:09 UTC, tomasdematos commented on src/components/AddCoin/AddCoin.tsx
> +                        placeholder={'Use a name or ticker symbol...'}
unnecessary { }

use: placeholder="Use a name...."

2023-03-30 22:11 UTC, tomasdematos commented on src/components/Header/Header.tsx
> +const Header = () => {
use implicit return

2023-03-30 23:58 UTC, jhonnierandrey commented
Not longer needed.

2023-03-30 23:58 UTC, closed without merging